using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace Fundraising_PT.Formularios
{
    public partial class UI_Graficos : DevExpress.XtraEditors.XtraForm
    {
        public UI_Graficos()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            chartControl1.DataSource = new System.Collections.Generic.List<Fundraising_PTDM.FUNDRAISING_PT.Recaudacion_Det>();
        }
    }
}